crowdstrikeConfig:
  clientID: "b801274e47134aa8b8b642d8e559c46c"
  clientSecret: "Nv1eHSKL8P6ctQ53aVuWClO0h7pm4RYdTi29ygfF"
executor:
  image:
    registry: ""
    repository: ""
    tag: ""
  dbStorage:
    create: false
    existingClaimName: falcon-executor-db
    accessModes:
      - ReadWriteOnce
    storageClass: ""
  assessmentStorage:
    type: PVC
    pvc:
      storageClass: ""
jobController:
  image:
    registry: ""
    repository: ""
    tag: ""
  dbStorage:
    create: true
    existingClaimName: ""
    storageClass: ebs-sc
    size: 1Gi
    accessModes:
      - ReadWriteOnce
registryConfigs:
  - type: nexus
    credentials:
      username: "admin"
      password: "password.1"
    allowedRepositories: ""
    host: http://172.31.26.134:5001
    cronSchedule: 0 * * * *
